#ifndef ANIM_NAMES_H
#define ANIM_NAMES_H


namespace AnimNames
{

	enum AnimName
	{
		// Claire
		S_CLAIRE_BASS,
		S_CLAIRE_DANCE_HIGH_KICK,
		S_CLAIRE_FIST_PUMP,
		S_CLAIRE_IDLE_HAPPY_SWAY,

		// ChickenBot
		S_CHICKENBOT_IDLE,
		S_CHICKENBOT_WALK,
		S_CHICKENBOT_RUN,
		S_CHICKENBOT_DIE_L,
		S_CHICKENBOT_DIE_R,
		S_CHICKENBOT_HIT_B,
		S_CHICKENBOT_HIT_F,
		S_CHICKENBOT_HIT_L,
		S_CHICKENBOT_HIT_R,
		S_CHICKENBOT_SHOT_D,
		S_CHICKENBOT_SHOT_F,
		S_CHICKENBOT_SHOT_U,
		S_CHICKENBOT_SIDESTEP_L,
		S_CHICKENBOT_SIDESTEP_R,
		S_CHICKENBOT_TURN_L,
		S_CHICKENBOT_TURN_R,

		// Grandma
		S_GRANDMA_CHEER,
		S_GRANDMA_DANCE_BBOY_HH,
		S_GRANDMA_DANCE_MACARENA,
		S_GRANDMA_IDLE,
		S_GRANDMA_RAP,
		S_GRANDMA_VICTORY,

		// Knight
		S_KNIGHT_CLAP_SIT,
		S_KNIGHT_IDLE_HAPPY,
		S_KNIGHT_PIANO,
		S_KNIGHT_IDLE_SIT,
		S_KNIGHT_DANCE_SILLY,

		// Michelle
		S_MICHELLE_CHEER,
		S_MICHELLE_IDLE,
		S_MICHELLE_REACT,
		S_MICHELLE_TALK,
		S_MICHELLE_DANCE_MARA_STEP,
		S_MICHELLE_DANCE_NSS_COMBO,

		// Mouse
		S_MOUSE_DANCE_JAZZ,
		S_MOUSE_DANCE_SALSA,
		S_MOUSE_DANCE_SILLY,
		S_MOUSE_DANCE_TWERK,
		S_MOUSE_IDLE,
		S_MOUSE_GUITAR,
		S_MOUSE_JOYFUL_JUMP,
		S_MOUSE_RUN_GOOFY,
		S_MOUSE_WALK,

		// Ninja
		S_NINJA_CHEER,
		S_NINJA_DANCE_FLAIR,
		S_NINJA_DANCE_HOUSE,
		S_NINJA_IDLE,
		S_NINJA_JAM,
		S_NINJA_PUSH_UP,

		// Ortiz
		S_ORTIZ_CHEER,
		S_ORTIZ_DANCE,
		S_ORTIZ_JAM,
		S_ORTIZ_DANCE_SWING,
		S_ORTIZ_IDLE,

		// Paladin
		S_PALADIN_BASS,
		S_PALADIN_CHEER,
		S_PALADIN_DANCE_HOKEY_POKEY,
		S_PALADIN_DANCE_SILLY,
		S_PALADIN_IDLE_HAPPY,

		// Pumpkin Hulk
		S_PUMPKIN_HULK_DRUMS,
		S_PUMPKIN_HULK_DANCE_HOKEY_POKEY,
		S_PUMPKIN_HULK_EXCITED,
		S_PUMPKIN_HULK_IDLE,
		S_PUMPKIN_HULK_IDLE_SIT,
		S_PUMPKIN_HULK_FIST_PUMP_SITTING,

		// Vanguard
		S_VANGUARD_CHEER,
		S_VANGUARD_DANCE_SALSA_1,
		S_VANGUARD_DANCE_SALSA_2,
		S_VANGUARD_IDLE_HAPPY,
		S_VANGUARD_JAM,
		S_VANGUARD_SING,

		// Zombie Girl
		S_ZOMBIE_GIRL_AGONIZE,
		S_ZOMBIE_GIRL_CHEER,
		S_ZOMBIE_GIRL_DANCE_MARA_STEP,
		S_ZOMBIE_GIRL_DANCE_YMCA,
		S_ZOMBIE_GIRL_IDLE_THRILLER,


		BLEND_ANIM,
		NULL_ANIM,

		UNINITIALIZED
	};

	const char* Stringify(AnimName name);
	const char* GetFileName(AnimName name);
}

// Automatic using on include
using namespace AnimNames;

#endif // !ANIM_NAMES_H
